services:
  - docker:dind

stages:
  - test
  - build
  - publish

# GLOBAL VARIABLES
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  PHOENIX_CHART_MAIN_DIR: charts/main
  PHOENIX_CHART_MAIN_PACKAGE_PATH: phoenix_chart_main

# Run linting for console_ui
console_ui_linting:
  image: node:21.6.2
  stage: test
  script:
    - cd console_ui/
    - npm install
    - npm run lint


python_build_and_ci_projects:
  image: docker:latest
  stage: test
  script:
    - cd python
    - docker build --build-arg PROJECT=$PROJECT -t $PROJECT .
    - docker run $PROJECT make all path=projects/$PROJECT
  parallel:
    matrix:
      - PROJECT: [example_project_1, phoenix_superset]

python_ci_libs:
  stage: test
  image: python:3.11.8
  script:
    - cd python
    - make install path=libs/$LIB
    - make all path=libs/$LIB
  parallel:
    matrix:
      - LIB: [example_lib_1]

python_projects_phiphi_ci:
  image: docker:latest
  stage: test
  script:
    - apk update && apk add make
    - cd python/projects/phiphi/
    - make all

lint_phoenix_chart_main:
  stage: test
  image:
    name: alpine/helm:3.11.1
    # This is needed or will get an error that helm cannot be run
    entrypoint: [""]
  needs: [] # Allows to run this job without waiting for the previous ones
  script:
    - helm lint $PHOENIX_CHART_MAIN_DIR

package_phoenix_chart_main:
  stage: build
  image:
    name: alpine/helm:3.11.1
    # This is needed or will get an error that helm cannot be run
    entrypoint: [""]
  needs: ["lint_phoenix_chart_main"]
  script:
    - helm package $PHOENIX_CHART_MAIN_DIR -d $PHOENIX_CHART_MAIN_PACKAGE_PATH
  artifacts:
    paths:
      - $PHOENIX_CHART_MAIN_PACKAGE_PATH/*.tgz
    # Going to pushed to package registry so it is fine to expire
    expire_in: 1 hour

publish_phoenix_chart_main:
  stage: publish
  image: curlimages/curl:7.70.0
  script:
    # There should only be one file in the PACKAGE_PATH directory
    # This command gets the file name
    - PACKAGE_FILE="$(ls -tr ${PHOENIX_CHART_MAIN_PACKAGE_PATH}/*.tgz | tail -1)"
    - echo "Publishing $PACKAGE_FILE"
    # Publish the package to the GitLab package registry
    # https://docs.gitlab.com/ee/user/packages/helm_repository/#use-cicd-to-publish-a-helm-package
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${PACKAGE_FILE}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
    - echo "Package published successfully. Use command"
    - echo "helm repo add phoenix_chart_main ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
  needs:
    - job: package_phoenix_chart_main
      artifacts: true
  rules:
    # Only run on `main` branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
