# Run linting for console_ui

stages:
  - lint

console_ui_linting:
  image: node:21.6.2
  stage: lint
  script:
    - cd console_ui/
    - npm install
    - npm run lint

# Run tests for the python projects
stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

python_build_and_ci_projects:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - cd python
    - docker build -t $PROJECT_NAME .
    - docker run $PROJECT_NAME make all path=projects/$PROJECT_NAME
  parallel:
    matrix:
      - PROJECT_NAME: [example_project_1]
  rules:
    - if: '$CI_MERGE_REQUEST_ID'

python_ci_libs:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  image: python:3.11.8
  script:
    - cd python
    - make install path=libs/$LIB_NAME
    - make all path=libs/$LIB_NAME
  parallel:
    matrix:
      - LIB_NAME: [example_lib_1]
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
