# The Gitlab CI is set up so that if your branch is called `ci/*` it will run the CI
# To run jobs that are only on main you can add the rule:
# - if: $CI_COMMIT_BRANCH =~ /^ci\/*/
.docker_template:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


# As based on this:
# https://docs.gitlab.com/ee/ci/yaml/workflow.html#git-flow-with-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

services:
  - docker:dind

stages:
  - pre_build
  - test
  - build
  - publish

# GLOBAL VARIABLES
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  PHOENIX_CHART_MAIN_DIR: charts/main
  PHOENIX_CHART_MAIN_PACKAGE_PATH: phoenix_chart_main
  PHOENIX_SUPERSET_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/phoenix_superset
  PHOENIX_SUPERSET_TEST_IMAGE: $PHOENIX_SUPERSET_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  PHOENIX_SUPERSET_LATEST_IMAGE: $PHOENIX_SUPERSET_REGISTRY_IMAGE:latest
  PHOENIX_SUPERSET_RELEASE_IMAGE: $PHOENIX_SUPERSET_REGISTRY_IMAGE:stable
  PRE_BUILD_IMAGE_FOLDER: pre_build_images
  PYTHON_IMAGE_REGISTRY: $CI_REGISTRY_IMAGE/python

# Run linting for console_ui
console_ui_linting:
  image: node:21.6.2
  stage: test
  script:
    - cd console_ui/
    - npm install
    - npm run lint
  needs: []


#######################
# Pre Build of the images for the python projects
#
# This speeds up the build process by building the images
# before the actual build and test process
#######################
python_images_pre_build:
  extends: .docker_template
  stage: pre_build
  script:
    - cd python
    # Refactor this to use the stable image as cache
    - docker build --build-arg PROJECT=$PROJECT -t $PROJECT .
    # Need to be in the correct folder for the artifacts to work
    - cd ..
    - mkdir -p $PRE_BUILD_IMAGE_FOLDER
    - docker save $PROJECT -o $PRE_BUILD_IMAGE_FOLDER/$PROJECT.tar
  artifacts:
    paths:
      - $PRE_BUILD_IMAGE_FOLDER/*.tar
    expire_in: 1 hour
  parallel:
    matrix:
      - PROJECT:
          - phiphi
          - phoenix_superset
          - example_project_1

python_ci_test:
  extends: .docker_template
  stage: test
  script:
    - docker load -i $PRE_BUILD_IMAGE_FOLDER/$PROJECT.tar
    - docker run $PROJECT make all path=projects/$PROJECT
  needs:
    - job: python_images_pre_build
      artifacts: true
  parallel:
    matrix:
      - PROJECT:
          - example_project_1
          - phoenix_superset

python_ci_libs:
  stage: test
  image: python:3.11.8
  script:
    - cd python
    - make install path=libs/$LIB
    - make all path=libs/$LIB
  parallel:
    matrix:
      - LIB: [example_lib_1]
  needs: []

#######################
# Test the phiphi project
#
# This is not in the generic python_ci_test job
# as it needs a database and other things to run correctly
#######################
python_phiphi_ci_test:
  extends: .docker_template
  stage: test
  script:
    - docker load -i $PRE_BUILD_IMAGE_FOLDER/phiphi.tar
    - apk update && apk add make
    - cd python/projects/phiphi/
    - make all
  needs:
    - job: python_images_pre_build
      artifacts: true
      parallel:
        matrix:
          - PROJECT: phiphi

lint_phoenix_chart_main:
  stage: test
  image:
    name: alpine/helm:3.11.1
    # This is needed or will get an error that helm cannot be run
    entrypoint: [""]
  needs: [] # Allows to run this job without waiting for the previous ones
  script:
    - helm lint $PHOENIX_CHART_MAIN_DIR

package_phoenix_chart_main:
  stage: build
  image:
    name: alpine/helm:3.11.1
    # This is needed or will get an error that helm cannot be run
    entrypoint: [""]
  needs: ["lint_phoenix_chart_main"]
  script:
    - helm package $PHOENIX_CHART_MAIN_DIR -d $PHOENIX_CHART_MAIN_PACKAGE_PATH
  artifacts:
    paths:
      - $PHOENIX_CHART_MAIN_PACKAGE_PATH/*.tgz
    # Going to pushed to package registry so it is fine to expire
    expire_in: 1 hour

build_phoenix_superset_image:
  extends: .docker_template
  stage: build
  script:
    - cd python/projects/phoenix_superset
    - docker build --pull -t $PHOENIX_SUPERSET_TEST_IMAGE .
    - docker tag $PHOENIX_SUPERSET_TEST_IMAGE $PHOENIX_SUPERSET_LATEST_IMAGE
    - docker push $PHOENIX_SUPERSET_TEST_IMAGE
    - docker push $PHOENIX_SUPERSET_LATEST_IMAGE
  needs:
    - job: python_ci_test
      parallel:
        matrix:
          - PROJECT: phoenix_superset


#######################
# Build the python images
#######################
python_images_build:
  extends:
    - .docker_template
  stage: build
  script:
    - docker load -i $PRE_BUILD_IMAGE_FOLDER/$PROJECT.tar
    - docker tag $PROJECT $PYTHON_IMAGE_REGISTRY/$PROJECT:$CI_COMMIT_REF_SLUG
    - docker tag $PROJECT $PYTHON_IMAGE_REGISTRY/$PROJECT:latest
    - docker push $PYTHON_IMAGE_REGISTRY/$PROJECT:$CI_COMMIT_REF_SLUG
    - docker push $PYTHON_IMAGE_REGISTRY/$PROJECT:latest
  parallel:
    matrix:
      - PROJECT:
          - phiphi
          # Add to show how to use
          - example_project_1
          # phoenix_superset is built in a separate job as it doesn't use the default python image
          # for the release
  needs:
    - job: python_images_pre_build
      artifacts: true
    - job: python_ci_test
      parallel:
        matrix:
          # If an other generic python project is added it should be added here
          - PROJECT: example_project_1
    - job: python_phiphi_ci_test

publish_phoenix_chart_main:
  stage: publish
  image: curlimages/curl:7.70.0
  script:
    # There should only be one file in the PACKAGE_PATH directory
    # This command gets the file name
    - PACKAGE_FILE="$(ls -tr ${PHOENIX_CHART_MAIN_PACKAGE_PATH}/*.tgz | tail -1)"
    - echo "Publishing $PACKAGE_FILE"
    # Publish the package to the GitLab package registry
    # https://docs.gitlab.com/ee/user/packages/helm_repository/#use-cicd-to-publish-a-helm-package
    - curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@${PACKAGE_FILE}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"
    - echo "Package published successfully. Use command"
    - echo "helm repo add phoenix_chart_main ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable"
  needs:
    - job: package_phoenix_chart_main
      artifacts: true
  rules:
    # Only run on `main` branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish_phoenix_superset_image:
  stage: publish
  extends: .docker_template
  script:
    - docker pull $PHOENIX_SUPERSET_TEST_IMAGE
    - docker tag $PHOENIX_SUPERSET_TEST_IMAGE $PHOENIX_SUPERSET_RELEASE_IMAGE
    - docker push $PHOENIX_SUPERSET_RELEASE_IMAGE
  needs:
    - job: build_phoenix_superset_image
  rules:
    # Only run on `main` branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish_phoenix_superset_image_tags:
  stage: publish
  extends: .docker_template
  script:
    - docker pull $PHOENIX_SUPERSET_TEST_IMAGE
    - docker tag $PHOENIX_SUPERSET_TEST_IMAGE $PHOENIX_SUPERSET_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $PHOENIX_SUPERSET_REGISTRY_IMAGE:$CI_COMMIT_TAG
  needs:
    - job: build_phoenix_superset_image
  rules:
    - if: $CI_COMMIT_TAG

#######################
# Publish the python images
#######################
publish_python_images:
  extends: .docker_template
  stage: publish
  script:
    - docker load -i $PRE_BUILD_IMAGE_FOLDER/$PROJECT.tar
    - docker tag $PROJECT $PYTHON_IMAGE_REGISTRY/$PROJECT:stable
    - docker push $PYTHON_IMAGE_REGISTRY/$PROJECT:stable
  parallel:
    matrix:
      - PROJECT:
          - phiphi
          # Add to show how to use
          - example_project_1
          # phoenix_superset is built in a separate job as it doesn't use the default python image
          # for the release
  needs:
    - job: python_images_pre_build
      artifacts: true
    - job: python_images_build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish_python_images_tags:
  extends: .docker_template
  stage: publish
  script:
    - docker load -i $PRE_BUILD_IMAGE_FOLDER/$PROJECT.tar
    - docker tag $PROJECT $PYTHON_IMAGE_REGISTRY/$PROJECT:$CI_COMMIT_TAG
    - docker push $PYTHON_IMAGE_REGISTRY/$PROJECT:$CI_COMMIT_TAG
  parallel:
    matrix:
      - PROJECT:
          - phiphi
          # Add to show how to use
          - example_project_1
          # phoenix_superset is built in a separate job as it doesn't use the default python image
          # for the release
  needs:
    - job: python_images_pre_build
      artifacts: true
    - job: python_images_build
  rules:
    - if: $CI_COMMIT_TAG
