console:
  enabled: true
  # Default oauth2 cookie name
  # Has to have cookie_httponly false
  env_auth_cookie: "_oauth2_proxy"
cert_issuer:
  enabled: false
cert-manager:
  enabled: false
oauth2-proxy:
  config:
    configFile: |
      # Settings for Auth0
      provider="oidc"
      provider_display_name="Auth0"
      oidc_issuer_url="https://dev-2ii4bfcaymdes14b.uk.auth0.com/"
      code_challenge_method="S256"
      http_address="0.0.0.0:4180"
      upstreams="file:///dev/null"
      email_domains="*"
      cookie_httponly=false
      # Important that this machtes the domain being used for the cluster
      cookie_domains=".phoenix.local"
      whitelist_domains=["*.phoenix.local:*", "dev-2ii4bfcaymdes14b.uk.auth0.com"]
      # email is needed as is not in default openid scrop
      scope="openid email"
      pass_access_token = true
      pass_authorization_header = true
      pass_user_headers = true
      set_xauthrequest = true
      cookie_samesite="lax"
      # To remove when secure version is used
      show_debug_on_error = true
      insecure_oidc_allow_unverified_email = true
      ssl_insecure_skip_verify=true
      cookie_secure="false"
superset:
  enabled: true
  # These secrets must be created before the first apply of the chart
  init:
    adminUser:
      email: buildup@datavaluepeople.com
  image:
    repository: phoenix_superset
    tag: latest
  configOverrides:
    general: |
      APP_NAME = "Dashboard - Phoenix"

      # This must be change in conjunction with the ingress auth-response-headers
      AUTH_REMOTE_USER_ENV_VAR = "HTTP_X_AUTH_REQUEST_EMAIL"

      # Throw error if got past the auth layer
      LOGIN_REDIRECT_URL = False
