"""instance_runs_model.

Revision ID: 0ed474a1c333
Revises: 6d4b2c6a304c
Create Date: 2024-04-17 07:57:45.266387

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ed474a1c333"
down_revision: Union[str, None] = "6d4b2c6a304c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE_NAME = "instance_runs"


def upgrade() -> None:
    """Upgrade for 0ed474a1c333."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        TABLE_NAME,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("started_processing_at", sa.DateTime(), nullable=True),
        sa.Column("environment_slug", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["instances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade for 0ed474a1c333."""
    op.drop_table(TABLE_NAME)
