"""Add_table_for_instances.

Revision ID: 099f8e0935ed
Revises: 371b7af746ab
Create Date: 2024-04-01 08:14:45.813096

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "099f8e0935ed"
down_revision: Union[str, None] = "371b7af746ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLE_NAME: str = "instances"


def upgrade() -> None:
    """Upgrade for 099f8e0935ed."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        TABLE_NAME,
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("environment_key", sa.String(), nullable=True),
        sa.Column("pi_deleted_after", sa.Integer(), nullable=True),
        sa.Column("deleted_after", sa.Integer(), nullable=True),
        sa.Column("expected_usage", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_instances_name"), TABLE_NAME, ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade for 099f8e0935ed."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instances_name"), table_name=TABLE_NAME)
    op.drop_table(TABLE_NAME)
    # ### end Alembic commands ###
