"""gathers_model.

Revision ID: 702b5ca2e315
Revises: f766ea48c9d1
Create Date: 2024-04-08 08:37:35.298464

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "702b5ca2e315"
down_revision: Union[str, None] = "f766ea48c9d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade for 702b5ca2e315."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gathers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("mark_to_delete", sa.Boolean(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("gather_type", sa.String(), nullable=False),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("config_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apify_gathers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("data_type", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("limit_messages", sa.Integer(), nullable=False),
        sa.Column("limit_replies", sa.Integer(), nullable=False),
        sa.Column("nested_replies", sa.Boolean(), nullable=False),
        sa.Column("input_data", sa.String(), nullable=False),
        sa.Column("input_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["gathers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade for 702b5ca2e315."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("apify_gathers")
    op.drop_table("gathers")
    # ### end Alembic commands ###
