"""updated_data_type_for_expected_usage.

Revision ID: ff0a93f2f65f
Revises: 099f8e0935ed
Create Date: 2024-04-01 09:40:33.292814

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff0a93f2f65f"
down_revision: Union[str, None] = "099f8e0935ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


TABLE_NAME = "instances"
COLUMN_NAME = "expected_usage"


def upgrade() -> None:
    """Upgrade for ff0a93f2f65f."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade for ff0a93f2f65f."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        TABLE_NAME,
        COLUMN_NAME,
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
