version: "3.8"
x-phoenix-bind:
  &default-bind
  type: bind
  source: ../../
  target: /app
  consistency: cached

services:
  api:
    image: "phiphi"
    env_file:
      - docker_env
    build:
      context: ../../
      args:
        PROJECT: phiphi
    volumes:
      - *default-bind
    entrypoint: /app/projects/phiphi/entrypoint.sh
    command: ["uvicorn", "phiphi.main:app", "--host", "0.0.0.0", "--port", "80"]
    ports:
      - "8080:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data:cached

volumes:
  db-data:
