# This file is used to run alembic commands in the container
# It is important to overwrite the entrypoint and working_dir
# So that we don't get an error when running alembic commands

services:
  api:
    entrypoint: /app/.docker-entrypoint.sh
    working_dir: /app/projects/phiphi/
