up:
	@echo "Starting up the development environment..."
	docker compose up

down:
	@echo "Shutting down the development environment..."
	docker compose down

build:
	@echo "Building the development environment..."
	docker compose build

clean:
	@echo "Clean the development environment..."
	docker compose down -v --remove-orphans
