{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c',
          'until pg_isready -h {{ tpl ( .Values.api.db_auth.host ) . }} -p {{ .Values.api.db_auth.port }} -U {{ .Values.api.db_auth.username }} -d {{ .Values.api.db_auth.database }}; 
          do echo waiting for database; sleep 2; done;']
      {{- if .Values.api.prefect_deployments.enabled }}
      - name: prefect-deployments
        {{- include "phoenixmain.phiphi_container" . | nindent 8 }}
        command: ["/app/projects/phiphi/entrypoint.sh"]
        args: [
          "python",
          "projects/phiphi/phiphi/prefect_deployments.py",
          "--image",
          {{ tpl (.Values.api.prefect_deployments.image ) . | quote }},
        ]
      {{- end }}
      containers:
      - name: phiphi
        {{- include "phoenixmain.phiphi_container" . | nindent 8 }}
        command: ["/app/projects/phiphi/entrypoint.sh"]
        args: [
          "uvicorn",
          "phiphi.api.main:app",
          {{- if .Values.api.reload }} "--reload", {{- end }}
          "--host", "0.0.0.0",
          "--port", "80",
          # Proxy headers are needed so that the redirects from the API have the correct
          # scheme and host. This is needed for the console to work correctly.
          "--proxy-headers"
        ]
      {{- if .Values.gcp_service_account.enabled }}
      volumes:
      - name: gcp-creds
        secret:
          secretName: {{ tpl (.Values.gcp_service_account.secret_name) . }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: 80
      targetPort: 80
{{- end -}}
