{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      initContainers:
      - name: check-db-ready
        image: postgres:9.6.5
        command: ['sh', '-c',
          'until pg_isready -h {{ tpl ( .Values.api.db_auth.host ) . }} -p {{ .Values.api.db_auth.port }} -U {{ .Values.api.db_auth.username }} -d {{ .Values.api.db_auth.database }}; 
          do echo waiting for database; sleep 2; done;']
      containers:
      - name: phiphi
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
          - containerPort: 80
        env:
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: {{ tpl ( .Values.api.secretKey ) . }}
                key: SQLALCHEMY_DATABASE_URI
          - name: CORS_ORIGINS
            value: {{ tpl ( .Values.api.cors_origins ) .}}
          - name: FIRST_ADMIN_USER_EMAIL
            value: {{ .Values.api.first_admin_user_email | quote }}
          - name: FIRST_ADMIN_USER_DISPLAY_NAME
            value: {{ .Values.api.first_admin_user_display_name | quote }}
          - name: HEADER_AUTH_NAME
            value: {{ .Values.api.header_auth_name | quote}}
          # There are alot of problems with setting the forwarded allow ips when used in the cli command.
          # For instances you have to do `--forwarded-allow-ips=*` with no quotes (double or single) around the *
          - name: FORWARDED_ALLOW_IPS
            value: {{ .Values.api.forwarded_allow_ips | quote}}
          - name: USE_MOCK_APIFY
            value: {{ .Values.api.use_mock_apify | quote }}
          - name: INCLUDE_INSECURE_AUTH
          {{- if .Values.use_local_insecure_auth }}
            value: "true"
          {{- else }}
            value: "false"
          {{- end }}
          {{- if .Values.gcp_service_account.enabled }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/{{ .Values.gcp_service_account.secret_key }}
          {{- end }}
          {{- if .Values.api.apify_api_keys.enabled }}
          - name: APIFY_API_KEYS
            valueFrom:
              secretKeyRef:
                name: {{ tpl ( .Values.api.apify_api_keys.secret_name ) . }}
                key: {{ .Values.api.apify_api_keys.secret_key }}
          {{- end }}
          {{- if and .Values.prefect .Values.prefect.apiKey }}
          - name: PREFECT_API_KEY
            valueFrom:
              secretKeyRef:
                name: prefect-api-key
                key: key
          {{- end }}
          {{- if index (index .Values "prefect-worker" ) "enabled" }}
          - name: PREFECT_API_URL
            # This uses the subchart to get the prefect-worker url
            value: {{ include "worker.apiUrl" (index  .Subcharts "prefect-worker") }}
          {{- end }}
        command: ["/app/projects/phiphi/entrypoint.sh"]
        args: [
          "uvicorn",
          "phiphi.api.main:app",
          {{- if .Values.api.reload }} "--reload", {{- end }}
          "--host", "0.0.0.0",
          "--port", "80",
          # Proxy headers are needed so that the redirects from the API have the correct
          # scheme and host. This is needed for the console to work correctly.
          "--proxy-headers"
        ]
## This is the secret that is used to store the GCP service account json
      {{- if .Values.gcp_service_account.enabled }}
        volumeMounts:
        - name: gcp-creds
          mountPath: /var/secrets/google
          readOnly: true
      volumes:
      - name: gcp-creds
        secret:
          secretName: {{ tpl (.Values.gcp_service_account.secret_name) . }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - port: 80
      targetPort: 80
{{- end -}}
