{{- if .Values.console.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-console
spec:
  replicas: {{ .Values.console.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-console
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-console
    spec:
      containers:
      - name: phoenix-console
        image: {{ .Values.console.image.repository }}:{{ .Values.console.image.tag }}
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-console-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-console
  ports:
    - port: 80
      targetPort: 3000
{{- end -}}
