apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: public
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-signin: http://oauth.phoenix.local/oauth2/start?rd=http://$host$uri
    nginx.ingress.kubernetes.io/auth-url: http://phoenixchartmain-oauth2-proxy.default.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-groups, x-auth-request-email"
spec:
  ingressClassName: public
  rules:
    - host: superset.phoenix.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phoenixchartmain-superset
                port:
                  number: 8088
