apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- include "phoenixmain.authSignin" . | nindent 4 }}
    nginx.ingress.kubernetes.io/auth-url: http://{{ .Release.Name }}-oauth2-proxy.{{ .Release.Namespace }}.svc.cluster.local/oauth2/auth
    nginx.ingress.kubernetes.io/proxy-buffer-size: 512k
    nginx.ingress.kubernetes.io/auth-response-headers: "x-auth-request-user, x-auth-request-groups, x-auth-request-email"
    cert-manager.io/issuer: {{ .Values.cert_issuer.issuer_name }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if .Values.cert_issuer.enabled }}
  tls:
  - hosts:
      - superset.{{ .Values.base_host }}
      - api.{{ .Values.base_host }}
    secretName: main-ingress-phoenix-tls
  {{- end }}
  rules:
    - host: superset.{{ .Values.base_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-superset
                port:
                  number: 8088
    - host: api.{{ .Values.base_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api-service
                port:
                  number: 80
