{{- if index (index .Values "oauth2-proxy" ) "enabled" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-oauth-proxy
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClassName }}
    {{- if .Values.cert_issuer.enabled }}
    cert-manager.io/issuer: {{ .Values.cert_issuer.issuer_name }}
    {{- end }}
    {{- include "phoenixmain.ingress_cors" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  {{- if .Values.cert_issuer.enabled }}
  tls:
  - hosts:
      - oauth.{{ .Values.base_host }}
    secretName: oauth-phoenix-tls
  {{- end }}
  rules:
  - host: oauth.{{ .Values.base_host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-oauth2-proxy
            port:
              number: 80
        path: /
        pathType: Prefix
{{- end }}
