apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl .Values.api.secretKey . }}
  labels:
    app: {{ .Release.Name }}-api
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://{{ .Values.api.db_auth.username }}:{{ .Values.api.db_auth.password }}@{{ tpl .Values.api.db_auth.host . }}:{{ .Values.api.db_auth.port }}/{{ .Values.api.db_auth.database }}"
