apiVersion: v2
name: phoenix_chart_main
description: Application chart for phoenix
type: application

# To simplify the chart and versioning, we are using the same version for the app and the chart.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
# These values are used in the templating to define artifacts (e.g. image tags) and dependencies.
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# IMPORTANT:
# If you change this you have to update superset.image.tag in values.yaml
# This can not be done via the parent chart
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
version: 2.9.1
appVersion: "2.9.1"

dependencies:
- name: superset
  condition: superset.enabled
  version: "0.12.11"
  repository: "https://apache.github.io/superset"
- name: oauth2-proxy
  condition: oauth2-proxy.enabled
  version: "7.7.8"
  repository: "https://oauth2-proxy.github.io/manifests"
- name: cert-manager
  version: v1.15.1
  repository: https://charts.jetstack.io
  alias: cert-manager
  condition: cert-manager.enabled
- name: postgresql
  version: 15.5.12
  repository: https://charts.bitnami.com/bitnami
  # This is needed or will have name duplication with the postgresql chart in
  # superset
  alias: platformdb
  condition: platformdb.enabled
- name: prefect-worker
  repository: https://prefecthq.github.io/prefect-helm
  version: 2024.6.28162841
  condition: prefect-worker.enabled
- name: prefect-server
  repository: https://prefecthq.github.io/prefect-helm
  version: 2024.6.28162841
  condition: prefect-server.enabled
