apiVersion: v1
kind: Secret
metadata:
  name: phoenixchartmain-superset-env-override
  labels:
    app: phoenixchartmain-superset
    chart: superset-0.12.6
    release: "phoenixchartmain"
type: Opaque
stringData:
    # Generate with:
    # openssl rand -base64 42
    SUPERSET_SECRET_KEY: "<SET>"
    REDIS_HOST: "phoenixchartmain-redis-headless"
    REDIS_USER: ""
    REDIS_PORT: "6379"
    REDIS_PROTO: "redis"
    REDIS_DB: "1"
    REDIS_CELERY_DB: "0"
    DB_HOST: "phoenixchartmain-postgresql"
    DB_PORT: "5432"
    DB_USER: "superset"
    DB_NAME: "superset"
    # This is the password that superset will use
    # Generalte with: openssl rand -base64 20
    DB_PASS: "superset"
    # Postgres secrets
    # The password has to match DB_PASS
    password: "superset"

    # If these are changed then they need to be added to
    # the values.yaml file
    # superset.postgresql.auth.username
    # superset.postgresql.auth.database
    username: "superset"
    database: "superset"
    # All these are needed for the postgres password to be set in the bitanmi chart
    postgres-password: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenixchartmain-oauth2-secrets
  labels:
    app: phoenixchartmain-oauth2
    release: "phoenixchartmain"
type: Opaque
stringData:
    # This can be generated with
    # openssl rand -base64 24
    cookie-secret: "<SET>"
    # Should be from the client
    client-secret: "<SET>"
    client-id: "<SET>"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenix-platform-db-secret
  labels:
    app: phoenix-platform-db
    release: "phoenixchartmain"
type: Opaque
stringData:
    ## For testing purposes postgres is fine to use
    db_user: "postgres"
    db_password: "<PASS SET>"
    db_name: "platform"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenix-api-secret
  labels:
    app: phoenix-api
    release: "phoenixchartmain"
type: Opaque
stringData:
  # These values must match a number of things in the chart:
  #
  # - PASS SET must match `db_password` in the platform-db-secret or the external db.
  # - ://postgres: is the user name and must match the db_user in the
  # platform-db-secret or the external db.
  # - @phoenixchartmain-platformdb:5432 is the host and
  # port of the db. It must match the `release name`-platformdb in the
  # - /platform is the db name and must match the.
  # - db_name in the platform-db-secret or the external db
  SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://postgres:<PASS SET>@phoenixchartmain-platformdb:5432/platform"
  # This is needed for the app to run but is not used in the app
  # It should be refactored so that the app can start with out it or with False
  SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://postgres:<PASS SET>@phoenixchartmain-platformdb:5432/platform_testing"
