# Superset
superset:
  enabled: true

# This is the base host that will be used for all ingress resources
base_host: "phoenix.local"

# The ingress class to use
# Public is the one needed for microk8s
ingressClassName: "public"


superset:
  configOverrides:
    # This will configure the branding of the application
    brand: |
      # White label settings
      APP_NAME = "Visual - Phoenix"
      APP_ICON = "/static/assets/images/logo_buildup_short_200.png"
      APP_ICON_WIDTH = 200
      FAVICONS = [
          {
              "rel": "apple-touch-icon",
              "sizes": "180x180",
              "href": "/static/assets/images/apple-touch-icon.png",
          },
          {"rel": "icon", "sizes": "32x32", "href": "/static/assets/images/favicon-32x32.png"},
          {"rel": "icon", "sizes": "16x16", "href": "/static/assets/images/favicon-16x16.png"},
      ]
