# Simple dev dockerfile that can be used in the local cluster
FROM node:18-alpine as base
RUN apk add --no-cache g++ make py3-pip libc6-compat
WORKDIR /app

ENV NODE_ENV=development
COPY . .
RUN npm install
CMD npm run dev
