# ref: https://docs.astral.sh/ruff/rules/
[tool.ruff]
include = ["*.py", "*.pyi", "**/pyproject.toml", "*.ipynb"]
target-version = "py311"
line-length = 99

[tool.ruff.lint]
select = [
  "F", # pyflakes
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "D", # pydocstyle
  "I", # isort
  "N", # pep8-naming
  "C90", # mccabe
  "PD", # pandas-vet
  "PGH", # pygrep-hooks
]
unfixable = ["F401"]
pydocstyle.convention = "google"

[tool.mypy]
python_version = "3.11"
# enforce all functions need type hints
disallow_untyped_defs = true
# all imported defs must have type hinds
disallow_any_unimported = true
# my uses a cache to speed up checking
incremental = true
# mypy will error if a config is set but not necessary
warn_unused_configs = true
# mypy will error if ignore comment is used on a non-erroring line
warn_unused_ignores = true
# mypy check Any values returned from functions
warn_return_any = true
# mypy will check the body of defs even if they don't have type sig
check_untyped_defs = true
# mypy with error if an unnecessary cast is used
warn_redundant_casts = true
# setting default arg to None still requires `Optional`
no_implicit_optional = true
# mypy checks the use of None values
strict_optional = true
# mypy follows and checks imported modules, gives more coverage
follow_imports = "normal"
# mypy follows and checks imported modules even without __init__.py
# WARN: this will still miss non-imported modules like test files with __init__.py
namespace_packages = true
# mypy prepends errors with the corresponding error code
show_error_codes = true

[[tool.mypy.overrides]]
module = "*.tests.*"
# remove enforce all functions need type hints within tests dir
disallow_untyped_defs = false

[tool.pytest.ini_options]
addopts = "--cov=acfp --cov-report term --cov-report xml:coverage.xml --durations=10"
