apiVersion: v1
kind: Secret
metadata:
  name: phoenixchartmain-superset-env-override
  namespace: default
  labels:
    app: phoenixchartmain-superset
    chart: superset-0.12.6
    release: "phoenixchartmain"
type: Opaque
stringData:
    # Generate with:
    # openssl rand -base64 42
    SUPERSET_SECRET_KEY: "<SET>"
    REDIS_HOST: "phoenixchartmain-redis-headless"
    REDIS_USER: ""
    REDIS_PORT: "6379"
    REDIS_PROTO: "redis"
    REDIS_DB: "1"
    REDIS_CELERY_DB: "0"
    DB_HOST: "phoenixchartmain-postgresql"
    DB_PORT: "5432"
    DB_USER: "superset"
    DB_NAME: "superset"

    # THis is the password that superset will use
    # Generalte with: openssl rand -base64 20
    DB_PASS: "<SET>"
    # All these are needed for the postgres password to be set in the bitanmi chart
    POSTGRES_PASSWORD: "<SET>"
    postgres-password: "<SET>"
    password: "<SET>"
---
apiVersion: v1
kind: Secret
metadata:
  name: phoenixchartmain-oauth2-secrets
  namespace: default
  labels:
    app: phoenixchartmain-oauth2
    release: "phoenixchartmain"
type: Opaque
stringData:
    # This can be generated with
    # openssl rand -base64 24
    cookie-secret: "<SET>"
    # Should be from the client
    client-secret: "<SET>"
    client-id: "<SET>
