[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "phoenix_superset"
version = "0.1.0"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["phoenix_superset"]
exclude = ["assets"]
